### ISSUE TITLE
DisplayFlush equivalent in wl package?

### ISSUE THREAD

**Issue by abenz1267** [neurlang/wayland#7]
Hi,

I'm currently building something with GTK4 and Wayland and I've successfully managed to use this wonderful library to implement https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1. However:

I'm running into an issue where at certain conditions the application would freeze or I can't "zwlr_foreign_toplevel_handle_v1:request:activate".

Looking it other pure C code, I noticed `wl_display_flush` being used.

How can I use `libwayland.func DisplayFlush(d *Display) (n int, err error)` with a `wl.Display`?

I tried moving to libwayland directly, but then got stuck on registering the protocol, since there's no `wl_registry_bind` equivalent in `libwayland`.

Regards

**Comment by neurlang** [comment]
In general there are two ways to use this project,
A) via the underlying libwayland C library (https://pkg.go.dev/github.com/neurlang/wayland/libwayland)
B) without involving C at all - via wl (https://pkg.go.dev/github.com/neurlang/wayland/wl) or it's highlevel wrapper window (https://pkg.go.dev/github.com/neurlang/wayland@v0.1.35/window)

A) **libwayland**
* if your app uses 3d graphics (vulkan, opengl, whatever), you must use A) **libwayland**
* used by the [go-wayland-cube](https://pkg.go.dev/github.com/neurlang/wayland@v0.1.35/go-wayland-cube) demo (3d cube)
* requires CGO (calling C from go), therefore you are unable to use the "cool" features of pure golang like race decector, possibly fuzzer like pure golang projecs can.
* this project's libwayland api is **incomplete** (PRs welcome)
* [DisplayFlush](https://github.com/neurlang/wayland/blob/v0.1.35/libwayland/wayland.go#L721)(d *[Display](https://pkg.go.dev/github.com/neurlang/wayland@v0.1.35/libwayland#Display)) (n [int](https://pkg.go.dev/builtin#int), err [error](https://pkg.go.dev/builtin#error)) is available

B) **wl**
* this is a linux only lowlevel api
* used by the simple demos (simple shm, image viewer)
* In general you do not need to flush, the library writes everything automatically, and you handle the callbacks once they come from display.Context().Run() or from display.Context().RunTill(specific_callback_to_run_till)
*  If you need to flush, call display.Sync(), it will tell you a callback, if you are interested to run until that callback comes, run display.Context().RunTill(specific_callback_to_run_till), otherwise call  display.Sync() again or display.Context().Run() to run pretty much forever

B) **wl** + **wlclient**
* wlclient is a helper functions library which you can use on top of wl
* wlclient allows you to run your mainloop in a goroutine
* wlclient.DisplayRoundtrip() is basically a single flush
* wlclient.DisplayRun() is basically pretty much run forever
* see simple-shm demo how it flushes twice using wlclient.DisplayRoundtrip() after hooking up the RegistryAddListener(..)


B) **wl** + **window**
* in this case you run forever via window.DisplayRun(Display *Display)
* (d *Display) Exit() from other goroutine? XXX: Not thread safe

**Comment by neurlang** [comment]
If you want to hook in the C library GTK4 (QT, whatever) you again have two options:

* A) libwayland
* DisplayFlush(d *Display) (n int, err error) is available

* B) wl / wl + wlclient / window
* you have to tell the C library GTK4 (QT, whatever) to paint its window's content into a []byte (RGBA) or (BGRA)
* (optional - if the colors are wrong) convert between RGBA and BGRA using swizzle (https://pkg.go.dev/github.com/neurlang/wayland/external/swizzle)
* then you put the []byte on screen via wl / wl + wlclient / window

The whole point is getting the C library GTK4 (QT, whatever) to paint its window's content into a []byte using the API which they may or may not provide

Good luck

**Comment by neurlang** [comment]
Note to self, If you manage to get GTK4 to draw the window frame using the current linux distribution's theme (into a PNG file)
`DrawFrame(totalWidth, totalHeight int, titleText string, titleSub string, pngFileName string, bgColor uint32) error`
that alone might be a significant achievement, as other go users can then spawn a native looking windows with little effort and draw into the green area a size of which they can easily detect from the png.

**Comment by neurlang** [comment]
This is the idea
![justborder](https://github.com/user-attachments/assets/616f8e7f-c1f8-4a47-8d11-ac3fc977b4cd)
You can dump the frame just once, no need to do it in loop or anything special, really.
